### ISSUE TITLE
User accounts for volunteers

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#114]
We should make have volunteers log in before they add tags to the database. This way we can:

-  restrict this action to logged in users
-  monitor if volunteers are putting fraudulent tags in the database and block those that do
-  keep a leaderboard so that we can exploit that strange quirk of human psychology to motivate users to tag moar

We can also use these accounts for image submission in order to keep a leaderboard of "images submitted" there too. When submitting images of officers, people should have the option of using a pseudonym or the option of not logging in and being anonymous (including using Tor, which we currently allow and will continue to).

**Comment by freddymartinez9** [comment]
It looks like [Flask-Login](https://flask-login.readthedocs.io/en/latest/#cookie-settings) is the best bet for our use. Note: this **does not** implement secure storage of usernames and passwords so we would have to properly salt + hash + encrypt in our DB.  Some design principles for secure user management 
- Password change form should prompt users to re-login using `fresh_login_required` from Flask-Login.
- We should support the "remember me" functionality, but we should use `Alternative Tokens`. The reasoning for this is subtle but important. If we only use usernames to implement "remember me", the logout functionality will not work. The username can be replayed to the webserver and it will bypass authentication. Therefore, on login, the `Alternative Token` is assigned to the user and when they click logout, the alternative token is invalidated. Even session would get a new Alternative token. It's much harder to invalid usernames than Alternative tokes. 
- REMEMBER_COOKIE_SECURE should be set to true. This should use the `secure` header for strict HTTPS enforcing. (We only use HTTPS anyways in our NGINX rules but its better to be verbose in this case)
- login_manager.session_protection = "strong" to prevent stealing session cookies. 

"Anonymous" users might be hard to implement because in `Flask-Login` anonymous refers the following properties
```
is_active and is_authenticated are False
is_anonymous is True
get_id() returns None
```

However, nothing precludes a user from registering / loging in over Tor and we wouldn't know who they were even if they registered (although there are separate considerations for making this argument)
