### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#16]
There are a lot of officers in CPD - which can make for slow queries as the app tries to get a photo for thousands of officers. Let's have the app show 10-50 at a time.

**Comment by scuerda** [comment]
Do you have feelings on if you want to hard code the pagination intervals or expose on front-end for user to chose?

**Comment by redshiftzero** [comment]
I think it would be great to expose them to the user, but at first if we can get e.g. 8 officers shown per page that would be wonderful

**Comment by redshiftzero** [comment]
I will work on this next when I have a free moment but will leave it unassigned until then so if someone else gets to it, awesome :metal:

**Comment by scuerda** [comment]
@redshiftzero I'm working on pagination and I have a basic version working. However there is a conflict between pagination and sorting as it has been implemented. 

Since I'm only working w/ the test data I don't have a great handle on what the sorting is handling. Is it fair to assume that it is intended to push officers for which there is no tagged photo down to the bottom of the list? 

If so, there will need to be some changes in the primary officer query to allow for this alongside pagination since the current flow will only sort the subset of officers active within the current pagination item.

Any thoughts?

**Comment by redshiftzero** [comment]
Done, thanks @scuerda!
