### ISSUE TITLE
Search for multiple races at once

### ISSUE THREAD

**Issue by b-meson** [lucyparsons/OpenOversight#277]
This one is a bit tricky in terms of racial demographics

**Comment by redshiftzero** [comment]
Hmm... why? Note that the race information comes straight from the rosters we get. On a related note, we should definitely be able to search by more than one race, e.g. a single search should be possible for both white AND hispanic officers. Currently you must select one. Would that address the issue here?

**Comment by redshiftzero** [comment]
This is a dupe of #262
