### ISSUE TITLE
gunicorn not starting automatically in development VM

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#299]
Gunicorn does not start automatically in the development VM:

```
(oovirtenv)vagrant@vagrant-ubuntu-trusty-64:/vagrant/OpenOversight$ sudo tail -f /var/log/gunicorn/oo.log
    max_log_size, num_logs_to_keep)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/tmp/openoversight.log'
```

**Comment by freddymartinez9** [comment]
is this related to #127 ? ( which I think we closed as fixed)

**Comment by r4v5** [comment]
Not really. #127 was fallout from the refactoring where the application was unable to be started in a wsgi context. This _looks like_ just some permissioning issues with the log file oo tries to write, because gunicorn starts up as www-data instead of the `vagrant` user:
```python
root@vagrant-ubuntu-trusty-64:~# cat /etc/gunicorn.d/oo 
CONFIG = {
  'mode': 'wsgi',
  'environment': {
    'PYTHONPATH': '/home/vagrant/oovirtenv'
  },
  'working_dir': '/vagrant/OpenOversight',
  'user': 'www-data',
  'group': 'www-data',
  'python': '/home/vagrant/oovirtenv/bin/python',
  'args': (
    '--bind=0.0.0.0:3000',
    '--workers=3',
    '--timeout=30',

    '--log-level=error',
    'app:app',
  ),
}
```
As specced, it doesn't look like there's a hard-coded knob for user/group gunicorn runs as: https://github.com/stankevich/puppet-python#pythongunicorn
So we can either change the template (ew) or change the permissions on /tmp/openoversight.log to be rw for both user `vagrant` and group `www-data`. I'm trying the latter right now, and if it gets a working gunicorn, I'll have a PR in shortly.
