### ISSUE TITLE
Update tutorial or add documentation

### ISSUE THREAD

**Issue by ssempervirens** [lucyparsons/OpenOversight#485]
We now have features like adding news articles to officer profiles which are not documented for volunteers. We should either update our tutorial, or have external documentation

**Comment by redshiftzero** [comment]
Hmm. Good point. Sounds like we need.... ReadTheDocs 😎

**Comment by dismantl** [comment]
It would also be great to add the autogenerated database documentation, like [here](https://disman.tl/oo-docs/). Would that be something to add to the #488 PR, or should I start a different branch for that?

**Comment by redshiftzero** [comment]
A PR adding here is actually probably the best for now: https://github.com/lucyparsons/OpenOversight/blob/develop/CONTRIB.md

What to move to the docs on #488 is up for debate, so open to input there. We _could_ move developer docs there eventually (I gotta hook up readthedocs). I think at minimum we want user facing docs there (since it's annoying to expect regular people to use GitHub) to include:

* volunteer tutorial, 
* area coordinator tutorial, 
* answers to what is needed before we'll add a new department to OpenOversight

**Comment by redshiftzero** [comment]
Docs are now setup on readthedocs, they are deployed on merge. We now need to add pages of documentation for the most common questions, see: #717 #716 #715
