### ISSUE TITLE
Baltimore customizations

### ISSUE THREAD

**Issue by dismantl** [lucyparsons/OpenOversight#515]
Creating this issue to discuss the customizations to OpenOversight that we may want to do for our Baltimore deployment. I would say the customizations fall into two buckets:

### Database changes
I recently got a [detailed roster of BPD employees](https://www.muckrock.com/foi/baltimore-315/bpd-officer-records-52459/#comm-541129) that includes more types of info than what is currently tracked in OO. We want OO to be able to track all this info so it can be our canonical data source on BPD officers. Not all of this info needs corresponding UI elements, but some of it we may want to display.

I think the best way to do this may be using [Alembic branches with multiple bases](http://alembic.zzzcomputing.com/en/latest/branches.html#working-with-multiple-bases). That way we can keep track of DB migrations specific to Baltimore in a separate workflow.

### UI changes
These would include customization of existing pages (like including sequence numbers on officer profiles or adding additional language to the About page), and down the line possibly adding additional pages. I was thinking the best way to do this would be to create a Blueprint for baltimore that includes customized views. And then as long as the baltimore blueprint is registered with the Flask app before the main blueprint, it's customized views should take precedence. At least that's my understanding at least, I'm new to Flask.

Any thoughts on those ideas?

**Comment by redshiftzero** [comment]
The main question I have is: are you committed to having a _separate_ webserver? In the past year, we've been increasingly moving towards a more centralized architecture with multiple departments.  The pros/cons as I see them: 

### Pros: 

* Decentralized deployment model: no single point of failure.

### Cons: 

*  Cross-department tracking harder: unless we implement some method of synchronizing, we won't be able to track officers across departments if multiple OpenOversights get spun up.
* Volunteers on the main OpenOversight website that want to volunteer across multiple departments would have to register again on another deployment in the current architecture.
* Maintenance burden of maintaining a fork for OpenOversight Baltimore: since we won't be testing our changes against the fork (e.g. when we do more tricky database migrations as we did in 0.4.1), it's not unlikely that we will introduce breakage in the future which will be annoying on your side to sort out.
* Ops/deployment story/documentation is not yet particularly smooth.

Obviously the project is open source, so anyone is free to take this code and modify it as they like, that said, I wonder if a better path forward for this officer tracking effort is for us to pool resources in a single deployment and address the single point of failure concern via distributed backups and a disaster recovery plan (at minimum).

**Comment by redshiftzero** [comment]
For the interested observer, @dismantl and I had a chat in detail about next steps - I filed a few issues for the features we need to implement to support an instance of OpenOversight in Baltimore based on our convo. fwiw, as long as other groups are prepared for the long-term maintenance burden of running their own infra and don't want syncing with the main instance, then I see no problem with other groups running a version of this codebase on their own (noting that federation is not something that we are currently planning to support in the future, if people disagree with this happy to chat about it further). Links to those issues follow: 

> Including a list of involved court cases on officer profiles, using our other data sets.

the functionality in #438 and the ability to add links in the officer profile should suffice here for now

> We would want to allow users to file complaints about officers using BPD-specific forms.

Filed #528 for this

> We want to include info and contact for our organization

Filed #526 for this

> This is definitely something I can help with!

🙌 

I'm closing this issue in favor of more specific followups, feel free to file anything I missed @dismantl  :-)
