### ISSUE TITLE
Add ability to look up officer from photo

### ISSUE THREAD

**Issue by ejfox** [lucyparsons/OpenOversight#654]
Using the same technologies that law enforcement and private corporations use to track citizens, I think it would be useful to use the OpenOversight database to train a TensorFlow model which can then be used to perform lookups. 

The ideal user story would be:
+ Jane has an interaction with a police officer who fails to identify themselves
+ Jane takes a photo, or finds a photo of her talking to that officer
+ Jane goes to OpenOversight and uploads that photo and draws a box around the officers face
+ OpenOversight searches it's database of uploaded officer images and returns any officers that have a >50% match to that officer's face

<https://github.com/justadudewhohacks/face-api.js> 

This is something I'd like to attempt to tackle once I get more comfortable developing on the OpenOversight project- but I'm curious to hear from others if this is a worthwhile use of time.

**Comment by McEileen** [comment]
As noted by the [about section of OpenOversight](https://www.openoversight.com/about), OpenOversight is compliant with [Illinois's Biometric Information Privacy Act](http://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=3004&ChapterID=57) because the project does not perform facial recognition.  In order to remain compliant with BIPA, I would oppose incorporating facial recognition into OpenOversight.

I recognize that OpenOversight also exists in jurisdictions outside of Illinois, some of which do not have legislation against facial recognition.  Hypothetically, the project could incorporate facial recognition for only jurisdictions which don't have acts similar to BIPA.  I would still oppose this.  I'm concerned what would happen if a user accidentally uploads an officer from a state that does not allow biometric facial recognition to a department where it is allowed.  That error case could result in OO violating a local regulation against biometric facial recognition.

Thoughts?  Let me know if you disagree about the possibility of including facial recognition for only some departments.  Thanks for writing such a thorough user story!

**Comment by camfassett** [comment]
Hey @ejfox and @McEileen! Correct, we cannot perform racial recognition in the state of IL, but we've had discussions previously about doing this on a department by department basis. 

I personally am in favor of this, and I think there are ways to hard code to prevent facial recognition performed by OO on IL police departments. Would you have further concerns, @McEileen?

There is currently an open ticket re: facial recognition, see #8, where we'd discussed using Amazon Rekognition to do this. If you'd be interested in discussing other ways to do it, @ejfox, that ticket might be the better starting ground, so if no one objects, maybe we should close this ticket?

**Comment by ejfox** [comment]
@McEileen Really appreciate you taking the time to explain this, makes total sense to me. 

@camfassett Sounds good, sorry I missed #8 - thanks!
