### ISSUE TITLE
The "add new officer" form is broken

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#744]
When I try to add a new officer on staging, through the form at `officer/new`, it throws an internal server error.  

I tested it locally, and the error appears to be coming from adding an assignment.  Here are the relevant error messages:
```
AttributeError
AttributeError: 'int' object has no attribute '_sa_instance_state'

File "/usr/src/app/OpenOversight/app/main/views.py", line 543, in add_officer
officer = add_officer_profile(form, current_user)
File "/usr/src/app/OpenOversight/app/utils.py", line 142, in add_officer_profile
db.session.add(assignment)
```

**Comment by abandoned-prototype** [comment]
Because I thought it might be my changes I quickly search for the error message. Found this: https://stackoverflow.com/questions/16151729/attributeerror-int-object-has-no-attribute-sa-instance-state#16152945 Looking for this problem in the code it looks like the issue is the interaction of: https://github.com/lucyparsons/OpenOversight/blob/2a7a3451bb75cfe5ed7365625a3db5d45cc842a7/OpenOversight/app/utils.py#L133 and https://github.com/lucyparsons/OpenOversight/blob/2a7a3451bb75cfe5ed7365625a3db5d45cc842a7/OpenOversight/app/utils.py#L140
I confirmed that the issue seems to be only triggered if a `Unit` is selected.
