### ISSUE TITLE
Bug - Chicago PD reporting link is broken on openoversight.lucyparsonslabs.com

### ISSUE THREAD

**Issue by EMCain** [lucyparsons/OpenOversight#748]
I don't know if this is the correct place to report problems with specific instances of the project -- let me know who to contact if it isn't. 

Using an arbitrary officer as an example:

https://openoversight.lucyparsonslabs.com/complaint?officer_first_name=RITA&officer_middle_initial=M&officer_last_name=MARTINEZ&officer_star=9926&officer_image=%2Fstatic%2Fimages%2Fplaceholder.png

The button on this page directs me to `http://ipraportal.iprachicago.org/pls/htmldb/f?p=1503:12:2709570244836141` which gets an error "This site can’t be reachedipraportal.iprachicago.org’s server IP address could not be found."

**Comment by abandoned-prototype** [comment]
Thanks @EMCain! This is definitely the right place to report this and an important find. Seems like this link is just stored in a template, so we would need to find a new/working link to fix this. Potentially we could also work on storing those links together with the department in the database, so that we have a link not just for Chicago, but any department that has one

**Comment by ssempervirens** [comment]
Seems to me the correct link here should be https://www.chicagocopa.org/complaints/? If I can get a +1 on that, I can make that change today. Agreed @abandoned-prototype we should definitely store this link for every department.
