### ISSUE TITLE
Automate scraping

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#76]
We've been writing code to scrape social media, but we should definitely automate this more:
- Each scraper should run every day and automatically upload images into the `raw_images` table for volunteers to tag
- Each scraper should get only the images that have been put up since the last time we scraped
- Each scraper should be putting the timestamps into the database. We want to keep track of how old each photograph is if possible (currently, all photographs in the database do have timestamps tracking when they were inserted).

**Comment by JoshuaOpolko** [comment]
I've got access to the vagrant image and db. A couple of items:  
Would it be practical to store the associated data from each flickr picture in raw_images instead of creating a separate csv file for each group?  
Also need to think about location for storing newly downloaded/unreviewed pics in the local path. Should they be downloaded to cpd_pictures or OpenOversight where the script is kept?  
For the hash_img value would https://pypi.python.org/pypi/ImageHash be sufficient?
