### ISSUE TITLE
Add states to browse department page or separate department lists by states

### ISSUE THREAD

**Issue by ssempervirens** [lucyparsons/OpenOversight#797]
As of now, our browse department page lists the names of departments, but as we continue to add new departments in new cities, I'm worried this will get confusing. For example, I didn't know that the Chittenden County Sheriff's Office was in Vermont until I googled it. 

The easiest solution here would be to add the state name in parentheses or something after the name — so it would read Chittenden County Sheriff's Office (VT) or Chittenden County Sheriff's Office (Vermont). A perhaps better solution in the longer term would be to have departments organized by federal, and then states, so that each department is listed under a state heading. I'm fine with either but I think it would be useful to add states to the department names.
<img width="757" alt="Screen Shot 2020-08-13 at 4 35 37 PM" src="https://user-images.githubusercontent.com/20425838/90197688-343c2580-dd84-11ea-91ba-d8cb83647c3d.png">

**Comment by fritzdavenport** [comment]
See also (closed) https://github.com/lucyparsons/OpenOversight/issues/792
and https://github.com/lucyparsons/OpenOversight/issues/364

**Comment by abandoned-prototype** [comment]
Bumping this issue since it is still a problem and becomes bigger the more departments we are adding.
In my opinion in the longer term we should think about UI improvements, so people can find the departments they are interested in quicker, some of this is also discussed in #364.

For the short term (covered in this issue), I think we should add a state column to the department and make sure it is populated in all paths that create departments (via UI by administrator and flask command directly on the server).
Then for /browse we should organize the list by state (in alphabetic order) and add a header line with an `id`, so that /browse#NewYork brings you directly to the New York departments for example. Within each state the departments should also be ordered alphabetically 

For other places where we use a dropdown (e.g. /submit, /find) I think using the [optgroup tag](https://www.w3schools.com/TAgs/tag_optgroup.asp) makes sense, not sure how much work it would be to include that (ideally it's only one component we change) everywhere. If this is not feasible we could add the state abbreviation in brackets in front and then order alphabetically (e.g. `[IL] Chicago Police Department`)

**Comment by michplunkett** [comment]
The states have been added to the UI and in the DB. The next step is to meet with a UX person and come up with how to do filtering for the departments.

**Comment by michplunkett** [comment]
Gonna create another ticket for UX things regarding department searching as this ticket already has a bit too much work associated with it.
