### ISSUE TITLE
Display officer - assignment end date

### ISSUE THREAD

**Issue by abandoned-prototype** [lucyparsons/OpenOversight#825]
Assignments are the link between an officer and the rank they have and the unit they belong to. As such assignments have a start-date and an end-date (unfortunately named `resign_date` in our code).
However, the end-date of an assignment is not shown in the officer-view (see for example: https://openoversight.com/officer/11943). Additionally the form to add or edit an assignment also doesn't have an assignment end entry.

So I think we should fix both those issues.

**Comment by egfrank** [comment]
I can work on this! It seems pretty self-explanatory tbh. 

For writing tests, it seems like there are a three tests about editing assignments in `tests/routes/test_officer_and_department` but they all focus on editing the officer badge number. Should I just write a new test for adding and editing the resign date? 

Also btw noticed there isn't validation that the resign date comes after the start date, not sure if that's a problem at all though.

Anyway let me know if it's okay for me to start working on this!

**Comment by abandoned-prototype** [comment]
Great, I assigned it to you. Will reply to the other details later, but it sounds like you are on a good path

**Comment by abandoned-prototype** [comment]
> For writing tests, it seems like there are a three tests about editing assignments in tests/routes/test_officer_and_department but they all focus on editing the officer badge number. Should I just write a new test for adding and editing the resign date?

I think it's fine to add to the existing tests, maybe add new ones if you want to do a different approach or do additional tests

> Also btw noticed there isn't validation that the resign date comes after the start date, not sure if that's a problem at all though

Good call. I think it makes sense to validate that, at least with the data that comes from the form

**Comment by egfrank** [comment]
Thanks for the responses, it definitely was the right call to add to existing tests so you'll notice I changed some test names in `test_officers_and_department.py` to reflect that it generally was testing add/editing assignment.

I added validation which seems to be working fine. The biggest twist is that once I added the validation, I noticed that the validation errors were not actually making it to the UI when adding an assignment in the officer-view. This because in the add_assignment view, previously errors were simply being logged, but then the view redirected back to the main officer view, not including any form data that contained the errors.
