### ISSUE TITLE
New Incident Form has display bugs

### ISSUE THREAD

**Issue by McEileen** [lucyparsons/OpenOversight#840]
`<SPAN CLASS="TEXT-DANGER"></SPAN>` displays above several fields in the New Incident form.  
![NewIncidentFormBug](https://user-images.githubusercontent.com/5529982/96385043-3f824780-115f-11eb-8ba7-31a092746fae.png)

**Comment by Alexandre2006** [comment]
Hi! Could you assign me to this? I think I've found the problem. By the way, this is my first issue.

**Comment by McEileen** [comment]
I assigned you. Thanks for helping out!

**Comment by Alexandre2006** [comment]
> I assigned you. Thanks for helping out!

No problem!

**Comment by Alexandre2006** [comment]
Hi! Please check out my pull request. This is the easiest way to fix it (obviously) and makes no changes to the appearance other than removing the <span class=...

**Comment by Alexandre2006** [comment]
#842

**Comment by abandoned-prototype** [comment]
Interestingly, this only seems to happen in local development. Curious what the original intent of this was and if it is supposed to be working according to the flask-wtf forms.

**Comment by Alexandre2006** [comment]
I wasn't able to get a server to run this but it seems that this may be the issue. I had to use a développement server through docker.

**Comment by abandoned-prototype** [comment]
> I wasn't able to get a server to run this but it seems that this may be the issue. I had to use a développement server through docker.

Yeah, the docker environment is what we use for development. Unfortunately this doesn't perfectly line up with the code running behind openoversight.com and staging.openoversight.com, as seen in this case. Fortunately this time it revealed a bug before it showed up in production, but might also happen the other way round.

I looked into it, and this turns out to be another installment of the pip requirement weirdness, where we specify a particular version of a library (`Flask-WTF==0.14.3` in this case) but the library itself doesn't specify the version of its own requirements, `wtforms`in this example. Then there is a new version of the underlying library (happened back in April) and the libraries on production and development are suddenly different. And one change that was made was to escape the label content as pointed out in this issue: https://github.com/wtforms/wtforms/issues/315

**Comment by Alexandre2006** [comment]
Hi @abandoned-prototype! I added the stars back in my new pull request. #843
