### ISSUE TITLE
overflow Scrollbar on homepage

### ISSUE THREAD

**Issue by staranbeer** [lucyparsons/OpenOversight#889]
when the user first opens up the website, content is overflowing on the x axis.

**Comment by AshwanthramKL** [comment]
I'd like to work on this.

**Comment by abandoned-prototype** [comment]
Hi @AshwanthramKL. Welcome to the project! I am not sure that this issue is still present in our latest version.
Can you test it on https://staging.openoversight.com/ which has the most recent updates?
And if this issue is fixed, feel free to look around, there might be other front-end issues present that we haven't documented yet. Thank you!

**Comment by michplunkett** [comment]
Tested this on staging and it looks like this is fixed. Gonna close this bb.
